package com.christ.erp.services.dto.admission.applicationprocess;

import java.time.LocalDate;
import java.util.List;

import com.christ.erp.services.dto.common.SelectDTO;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class ApplicationListDTO {
	
	private int studentEntries;
	private SelectDTO academicYear;
	private SelectDTO selectionProcessSession;
	private List<SelectDTO> location;
	private List<SelectDTO> campusName;
	private SelectDTO level;
	private SelectDTO degree;
	private SelectDTO programmeName;
	private LocalDate submittedFrom;
	private LocalDate submittedTill;
	private String status;
	private String profilePhotoUrl;
	private List<Integer> studentEntriesIds;
	
	private boolean gridCheck;
	
	private String applicationNo;
	private String applicantName;
	private String dateofBirth;
	private String gender;
	private String emailID;
	private String mobileNo;
	private String submissionDate;
	private String programme;
	private String admissionYear;
	private String admissionType;
	private String intakeBatch;
	private String campus;
	private String preferences;
	private String specialisation;
	private String selectionProcessRound1;
	private String selectionProcessDateRound1;
	private String selectionProcessTimeRound1;
	private String selectionProcessVenueRound1;
	private String selectionProcessRound2;
	private String selectionProcessDateRound2;
	private String selectionProcessTimeRound2;
	private String selectionProcessVenueRound2;
	private String educationDetails;
	private String residentCategory;
	private String appliedBatch;
	private String verificationStatus;
	private String verifiedDate;
	private String verifiedUser;
	private String verificationRemarks;
	private String verificationAdditionalRemarks;
	private String totalWeightage;
	private String lastdateofFeePayment;
	private String applicationStatus;
	private String applicationStatusRemarks;
	private String applicationStatusUpdatedOn;
	private String applicantStatus;
	private String applicantStatusUpdatedOn;
	private String prerequisiteExamName;
	private String prerequisiteExamMonthYear;
	private String prerequisiteMaxmarks;
	private String prerequisiteMarks;
	private String prerequisiteRollNo;
	private String citizenship;
	private String bloodGroup;
	private String religion;
	private String reservationCategory;
	private String motherTongue;
	private String differentlyAbled;
	private String differentlyAbledDescription;
	private String aadhaarNo;
	private String aadhaarEnrollmentNo;
	private String pioOrOci;
	private String pioOrOciCardNo;
	private String placeofBirth;
	private String birthCountry;
	private String birthState;
	private String birthCity;
	private String birthPincode;
	private String sponsershipName;
	private String sponsershipEmail;
	private String sponsershipPhoneNumber;
	private String sponsershipCountry;
	private String passportNo;
	private String passportIssuedDate;
	private String passportExpiryDate;
	private String passportIssuedFrom;
	private String secondLanguage;
	private String researchTopicDetails;
	private String informationOnInstitution;
	private String currentAddress1;
	private String currentAddress2;
	private String currentAddressCity;
	private String currentAddressState;
	private String currentAddressCountry;
	private String currentAddressPin;
	private String permanentAddress1;
	private String permanentAddress2;
	private String permanentAddressCity;
	private String permanentAddressState;
	private String permanentAddressCountry;
	private String permanentAddressPin;
	private String fathersName;
	private String fatherEmailID;
	private String fatherMobileNo;
	private String fathersQualification;
	private String fathersOccupation;
	private String fathersIncome;
	private String mothersName;
	private String motherEmailID;
	private String motherMobileNo;
	private String mothersQualification;
	private String mothersOccupation;
	private String mothersIncome;
	private String familyIncome;
	private String guardiansName;
	private String guardiansEmailID;
	private String guardiansMobileNo;
	private String extraCurricularDetail;
	private String workExperienceDetails;
	private String totalPartTimeExperience;
	private String totalFullTimeExperience;
	private String christiteRegisterNo;

}
