package com.christ.erp.services.common;

public enum SysProperties {
    UNIVERSITY_NAME,
    PAYMENT_GATEWAY,
    ACCOUNT, FeesCode,
    EMPLOYEE_JOINING_INTIMATION_EMAIL,
    EMP_INTERVIEW_STAGE1_SELECTED_INTIMATION,
    LAST_EMAIL_SEND_FROM,
    RECENT_TAB_COUNT_MAX,
    ERP_INTIMATION_EMAIL, 
    COMMON_RECRUITMENT_OFFICE_MAIL_ID, 
    COMMON_RECRUITMENT_OFFICE_MOB_NO, 
    COMMON_RECRUITMENT_USER_ID;
}
