package com.christ.erp.services.dto.employee.recruitment;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import com.christ.erp.services.dto.aws.FileUploadDownloadDTO;
import com.christ.erp.services.dto.common.ExModelBaseDTO;
import com.christ.erp.services.dto.common.ModelBaseDTO;
import com.christ.erp.services.dto.common.SelectDTO;
import com.christ.erp.services.dto.employee.EmpPositionRoleSubDTO;
import com.christ.erp.services.dto.employee.salary.SalaryComponentDTO;

import lombok.Getter;
import lombok.Setter;
@Setter
@Getter
public class FinalInterviewCommentsDTO extends ModelBaseDTO {
//	public Boolean isSelected;
	public Boolean withPF;
    public Boolean withGratuity;
    public Boolean isESI;
    public Boolean isOfferLetterGenerated;
    public Boolean isOfferLetterRegenerated;
    public Boolean isVcComment;
	public String applicationId;
    public String applicationNumber;
    public String applicantName;
    public String appliedSubject;
    public String appliedSubjectSpecialization;
    public String selectedPayScaleType;
    public String grossPay;
    public String consolidatedAmount;
    public String dailyAmount;
    public String perHourAmount;
    public String perCourseAmount;
//    public String vcComments;
    public LocalDateTime reportingDateAndTime;
    public LocalDateTime joiningDateAndTime;
    public String minAmount;
    public String maxAmount;
    public String isEmployeeCategoryAcademic;
    public String subjectOrCategoryLable;
    public String mode;
    public String recognisedExpYear;
    public String recognisedExpMonth;
    public String basicPayAmount;
    public String genderName;
    public String age;
    public String dob;
    public LocalDate appliedDate;
    public String subjectCategoryName;
    public String expectedSalary;
    public String printDesignation;
    public String printGrossPay;
    public String printBasicValue;
    public String printScalePay;
    public String totalMaxScore;
    public String printRecognisedExpYear;
    public String printRecognisedExpMonth;
    public String printTotalExpYear;
    public String printTotalExpMonth;
    public String printJoiningTime;
    public String printApplicationNumber;
    public String printApplicantName;
    public String printSubjectCategoryName;
    public String printSubjectCategoryLable;
    public String printPerHourAmount;
    public String printPerCourseAmount;
    public String joiningDateAndTimeTag;
    public String reportingDateAndTimeTag;
    public String jobRejectionReason;
    public String applicationStatus;
    public List<ExModelBaseDTO> internalInterviewersCount;
    public List<ExModelBaseDTO> externalInterviewersCount;
    public Integer empDailyWageDetailsId;
    public ExModelBaseDTO campus;
    public ExModelBaseDTO category;
    public ExModelBaseDTO jobCategory;
    public ExModelBaseDTO empTitle;
    public ExModelBaseDTO subjectCategory;
    public ExModelBaseDTO designation;
    public ExModelBaseDTO grade;
    public ExModelBaseDTO revisedYear;
    public ExModelBaseDTO level;
    public ExModelBaseDTO scale;
    public ExModelBaseDTO cell;
    public ExModelBaseDTO cellValue;
    public ExModelBaseDTO subjectCategorySpecialization;
    public ExModelBaseDTO categoryAcademic;
    public List<ExModelBaseDTO> internalInterviewers;
    public List<ExModelBaseDTO> externalInterviewers;
    public List<EmpPositionRoleSubDTO> printEmpApplnDignitariesFeedback;
    public List<EmpPositionRoleSubDTO> processAndPosition;
    public List<SalaryComponentDTO> empPayScaleComponents;
    public List<EmpApplnEducationalDetailsDTO> qualificationLevelList;
    public List<EmpApplnInterviewTemplateGroupDTO> heading;
    public SelectDTO offerLetterTemplate;
    public SelectDTO  regretLetterTemplate;
    public String personalEmail;
    public String mobileNumber;
    public List<EmpApplnWorkExperienceDTO> empApplnWorkExperienceDTOList;
    private SelectDTO campusDeptDto;
    private String selectionStatus;
    private SelectDTO stage3InterviewedBy;
    private String stage3Comments;
    private FileUploadDownloadDTO offerLetterUrlDto;
    private FileUploadDownloadDTO regretLetterUrlDto;
    private String offerLetterPreview;
    private Boolean isRegretLetterGenerated;
    private String stage1HodComments;
    private LocalDateTime preferedJoiningDateTime;
    private String joiningDateRejectReason;
    private Boolean isJoiningDateConfirmed;
    private String stage2OnholdRejectedComments;
}
