package com.christ.erp.services.dto.employee.report;

import java.time.LocalDate;
import java.util.List;

import com.christ.erp.services.dto.common.SelectDTO;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class EmployeeListDTO {

	private int empId;
	private SelectDTO academicYear;
	private SelectDTO employeeCategory;
	private SelectDTO jobcategory;
	private SelectDTO school;
	private SelectDTO department ;
	private List<SelectDTO> campus ;
	private SelectDTO designation;
	private LocalDate asOnDate;
	private LocalDate empFromDate;
	private LocalDate empToDate;
	private String status;
	private List<Integer> empIds;
	
	
	private String empNo;
	private String empName;
	private String empGender;
	private String empDob;
	private String mobileNo;
	private String dateOfJoin;
	private String dateOfRetirement;
	private String contractStartDate;
	private String contractEndDate;
	private String contractRemarks ;
	private String active;
	private String officeMailID;
	private String personalMailID;
//	private String fathersName ;
//	private String mothersName;
	private String nationality ;
	private String maritalStatus;
	private String religion;
	private String reservationCategory;
	private String bloodGroup;
	private String differentlyAbled;
	private String disabilityType;
	private String currentAddress1;
	private String currentAddress2;
	private String currentAddressCity;
	private String currentAddressState;
	private String currentAddressCountry;
	private String currentAddressPinCode;
	private String permanentAddress1;
	private String permanentAddress2;
	private String permanentAddressCity;
	private String permanentAddressState;
	private String permanentAddressCountry;
	private String permanentAddressPinCode;
	private String empCategory;
	private String empJobcategory;
	private String subjectOrCategory;
	private String specialisation ;
	private String employeeGroup;
	private String empDesignation;
	private String designationforStaffAlbum;
	private String title;
	private String empDepartment; 
	private String empCampus;
	private String deputedDepartmentAndCampus;
	private String titleInDeputedDepartment;
	private String seatingLocation;
	private String extensionNo; 
	private String telephone;
	private String deputationStartDate;
	private String applicationNo;
	private String letterDetails;
	private String pfAccountNo;
	private String pfDate;
	private String uanNo;
	private String pfNomineeDetails;
	private String licGratuityNo;
	private String licGratuityDate;
	private String gratuityNomineeDetails;
	private String bankAccountNo;
	private String ifscCode;
	private String smartCardNo; 
	private String panNo;
	private String aadharNo;
	private String emergencyContactDetails;
	private String passportDetails;
	private String visaDetails;
	private String frroDetails;
	private String payScaleDetails;
	private String canDisplayInWebsite; 
	private String timeZone;
	private String hasVacation; 
	private String hasVacationTimeZone;
	private String vacationTimeZone;
	private String hasHolidayTimeZone;
	private String holidayTimezone;
	private String roasterAllotmentApplicable; 
	private String approverDetails;
	private String leaveCategory;
	private String guestAndContractDetails;
	private String previousExperienceFullTime;
	private String previousExperiencePartTime;
	private String recognisedExperience;
	private String experienceInCU ;
	private String totalCurrentExperience;
	private String highestQualification;
	private String highestQualificationForStaffAlbum;
	private String qualificationDetails;
	private String eligibilityTest;
	private String workExperience;
	private String majorAchievements;
	private String fourWheelerNo;
	private String twoWheelerNo;
	private String fathersName;
	private String mothersName;
	private String FamilyDetails;
	private String familyDependentDetails;
	private String resignationDetails;
	private String orcidNo;
	private String scopusId;

}
